services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.11
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: auction
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      CLICKHOUSE_HOST: clickhouse
    depends_on:
      - clickhouse
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  clickhouse_data:
